data_sources:

  - id: postgres_source
    description: Events Table in Postgres
    type: postgres
    host: 172.97.0.111
    port: 5432
    username: my_es_username
    password: my_es_password
    database: my_es_database
    table: event_store
    columns:
      - id
      - event_id
      - event_name
      - aggregate_id
      - aggregate_version
      - json_payload
      - json_metadata
      - recorded_on
      - causation_id
      - correlation_id
    serialColumn: id
    partitioningColumn: correlation_id

##########################

data_destinations: